# Generated by Django 3.0.1 on 2019-12-31 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('regularity', models.CharField(choices=[('N', 'original'), ('D', 'daily'), ('W', 'weekly'), ('M', 'monthly'), ('Y', 'annual')], default='N', max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
