# Generated by Django 3.0.1 on 2020-01-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
