version: '3'

services:
  web:
    # run wherever you want to update requirements and/or apply migrations
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
